### ISSUE TITLE
not nearly enough hotkeys

### ISSUE THREAD

**Issue by Limdel** [faho/kwin-tiling#53]
1) hotkeys to move/switch tiles in places
2) hotkeys for rezising
3) monocle view toggle (maximize/unmaximize all windows on desktop)
4) rotate desktop (like in bspwm)
5) flip and mirror desktop
6) hotkeys for switching focus

**Comment by faho** [comment]
>1) hotkeys to move/switch tiles in places

Already there.

> 2) hotkeys for rezising

Already there.

> 3) monocle view toggle (maximize/unmaximize all windows on desktop)

This could be put into a different script.

> 4) rotate desktop (like in bspwm)

> 5) flip and mirror desktop

What do these do, exactly?

> 6) hotkeys for switching focus

For these kwin's own hotkeys should be used - if there's any bugs in them (e.g. the selection is weird), they should be reported upstream and fixed there.

----

The large issue here is that, on Plasma 5, hotkeys are currently completely disabled (i.e. the code is commented out) because the API doesn't expose them (it's [an upstream bug](https://bugs.kde.org/show_bug.cgi?id=340225)).

**Comment by Limdel** [comment]
maybe I'm stupid or blind, but I didn't found any hotkeys that let you control everything with keyboard, like Alt+Right will switch window with the one that is on the right side of focused one, and Alt+Left will do the same for the left one. same for focus changing. the existing hotkeys that I swa can only toggle risize/move mode for the mouse.

**Comment by faho** [comment]
For focus changing:
![screenshot_20160215_151202](https://cloud.githubusercontent.com/assets/5185367/13050921/aed60140-d3f6-11e5-9ec5-9ccb1650e82c.png).

The others are in [the code](https://github.com/faho/kwin-tiling/blob/master/contents/code/tilingmanager.js#L181-L414), though as you can see, it's currently commented out because it doesn't work on Plasma 5.

**Comment by Limdel** [comment]
okay, thank you for response. great work though, will wait till it will be fully ported.

**Comment by inaugurator** [comment]
Ok, I wait good news about this bug.

**Comment by wilderjds** [comment]
If you exported them with dbus (is it possible for a script?) one could call them with xbindkeys perhaps? I know this is a workaround but for the time being it would be quite useful

**Comment by faho** [comment]
>If you exported them with dbus (is it possible for a script?)

Nope. We can make dbus _calls_, but we can't add any objects/methods/whatever of our own. Also this would be used by about 3 people (myself not included) so I don't think it'd be worth it either way.
