### ISSUE TITLE
Switching among windows with Super+<digit>

### ISSUE THREAD

**Issue by dandv** [faho/kwin-tiling#66]
Wanted to reply to you in this Reddit thread, but it's "archived" and I "won't be able to vote or comment" (Why the heck do they do this?)

So I've asked a question on AskUbuntu:

http://askubuntu.com/questions/813262/which-desktop-environments-allow-switching-among-windows-with-supernumbers

**Comment by faho** [comment]
This is something that's completely orthogonal to tiling.

I'd say it could be handled in another script, but there you'd run into problems (and I don't mean that you couldn't currently use QML because that breaks shortcuts).

The problem would be that there'd basically be no way to guarantee that you have the same ordering as your taskbar, so you'd essentially be flying blind. Maybe it'd be possible to write your own task plasmoid, or to add it to the existing ones? Maybe look in the KDE bugtracker?

Hope that helps!

**Comment by dandv** [comment]
> Maybe look in the KDE bugtracker?

Unfortunately the [search there is shit](https://bugs.kde.org/show_bug.cgi?id=367476).
