### ISSUE TITLE
Application Launcher is maximized

### ISSUE THREAD

**Issue by piotr-dobrogost** [faho/kwin-tiling#74]
Application Launcher is maximized when opened but it should not.

**Comment by faho** [comment]
Is it _maximized_ or tiled? Are you using commit e409fb7ad40b8850fa38a1a84d2cd33d21cd5a4d or later?

Can you run `sleep 5; xprop` in a terminal, then open the launcher, wait five seconds and click it when the mouse cursor turns into a cross? That'll give you some information on the window. The "WM_CLASS" line is interesting here, and it should be `WM_CLASS(STRING) = "plasmashell", "plasmashell"`.

**Comment by piotr-dobrogost** [comment]
> Is it maximized or tiled (i.e. are other windows pushed out of the way)?

It looks like it's maximized; launcher's window is semi transparent and I can see through that tiled windows stay when they were.

> Are you using commit e409fb7 or later?

I'm on tip.

> Can you run sleep 5; xprop in a terminal, then open the launcher, wait five seconds and click it when the mouse cursor turns into a cross? That'll give you some information on the window. The "WM_CLASS" line is interesting here, and it should be WM_CLASS(STRING) = "plasmashell", "plasmashell".

Below is whole output:
```
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) =
_NET_WM_NAME(UTF8_STRING) = "Plasma"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x1, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x2a00014
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: True
                Initial state is Normal State.
_NET_WM_PID(CARDINAL) = 1302
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 44040234
WM_CLASS(STRING) = "plasmashell", "plasmashell"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                user specified location: 1680, 0
                user specified size: 1920 by 1168
                program specified minimum size: 428 by 556
                program specified maximum size: 1920 by 1168
                window gravity: Static

```

**Comment by faho** [comment]
If it were maximized, it should have "_NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ" in the xprop output. That often contains ASCII-art versions of the app icon, maybe you didn't think to scroll past it?

Can you `grep floaters= ~/.config/kwinrc`?

In any case, as I've stated before we can't set maximization state, so it seems unlikely that we are doing that. It might be from one of your window rules, or it's possible that it was tiled (because you had a broken script version installed) and then remembered that size. Can you try resizing the launcher (i.e. hold down the windows-key or the alt-key and right mouse button, move the mouse)?

**Comment by piotr-dobrogost** [comment]
> Can you try resizing the launcher (i.e. hold down the windows-key or the alt-key and right mouse button, move the mouse)?

Yup, this way I was able to fix this (restore sane/original size).
Thanks for help.

**Comment by PietJanHein** [comment]
I had the same problem and I solved it in the same way. alt + right mouse button and grabbing the windows of Application Launcher. For me this happened on the currently most recent version of  Kubuntu, it happened because I maximized the window. It seems to me like the size of that windows should be locked but apparently it isn't. It is a rather annoying bug because it is not 'intuitive'  that you have to use these buttons to grab the window.
