### ISSUE TITLE
Compatibility with another script

### ISSUE THREAD

**Issue by huti26** [faho/kwin-tiling#91]
I'm not too sure if that is even something you can fix on your side, but I like to use this script: https://github.com/Aetf/kwin-maxmize-to-new-desktop, which creates a new virtual desktop and moves a window there, when you put it in fullscreen mode, just like in osx.

When I use this script and yours, whenever I put a window in fullscreen all other windows end up untiled and I have to press meta+T to retile them. Is there any workaround to fix this? Maybe some other users  use both scripts too and found a solution already.

**Comment by faho** [comment]
Sorry for missing this - it seems github's personal rss feed has become even more worthless than I thought!

>When I use this script and yours, whenever I put a window in fullscreen all other windows end up untiled

The issue is that both scripts react to a client becoming "fullscreen" - the tiling script by temporarily disabling tiling on that desktop, and the other one by moving the client.

In theory, the tiling script is supposed to get another signal to signify that the client moved, but it's possible that happens too early or something. I need to check that.

Note that, however, the tiling script is fairly invasive and I can't guarantee that it'll work with arbitrary other scripts.

**Comment by faho** [comment]
@huti26: Please try 3642559. There was an actual issue in the tiling script that it turns out I never hit.

Though I did manage to crash kwin a couple of times while testing this, so it's possible there's more issues there.

**Comment by huti26** [comment]
I just got the newest version and as far as I can tell, it works perfectly fine now.!
